{% set version = "0.0.30" %}

package:
  name: aeppl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aeppl/aeppl-{{ version }}.tar.gz
  sha256: 1205b76f05a3f7e1b2e721e7e82bd29c01201172754dd81e6eb27fcbd95c872f
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.18.1
    - scipy >=1.4.0
    - aesara >=2.1.1

test:
  imports:
    - aeppl

about:
  home: https://github.com/aesara-devs/aeppl
  license: MIT
  summary: PPL tools for Aesara
  license_file: LICENSE
  dev_url: https://github.com/aesara-devs/aeppl/

extra:
  recipe-maintainers:
    - brandonwillard
    - ricardoV94
    - twiecki
