{% set version = "0.0.15" %}

package:
  name: aeppl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aeppl/aeppl-{{ version }}.tar.gz
  sha256: 77538860d5ea8a5608301db98686c11969d662a83ba7b19e8ca94f884759a92e
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.18.1
    - scipy >=1.4.0
    - aesara >=2.1.1

test:
  imports:
    - aeppl

about:
  home: https://github.com/aesara-devs/aeppl
  license: MIT
  summary: PPL tools for Aesara
  license_file: LICENSE
  dev_url: https://github.com/aesara-devs/aeppl/

extra:
  recipe-maintainers:
    - brandonwillard
    - twiecki
